services:
  anvil:
    build:
      context: .
      dockerfile: ./docker/anvil/develop.Dockerfile
    tty: true
    ports:
      - 18545:8545

  app:
    build:
      context: .
      dockerfile: docker/app/develop.Dockerfile
    tty: true
    volumes:
      - .:/application
    ports:
      - 13000:3000 # frontend
      - 14943:4943 # icp
